/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframes;

/**
 *
 * @author User
 */
public class leaveRequestDashboard extends javax.swing.JFrame {

    /**
     * Creates new form leaveRequestHistory
     */
    public leaveRequestDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        editIcon8 = new javax.swing.JLabel();
        viewIcon8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        editIcon7 = new javax.swing.JLabel();
        viewIcon7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        editIcon6 = new javax.swing.JLabel();
        viewIcon6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        editIcon5 = new javax.swing.JLabel();
        viewIcon5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        editIcon4 = new javax.swing.JLabel();
        viewIcon4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        editIcon3 = new javax.swing.JLabel();
        viewIcon3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        editIcon = new javax.swing.JLabel();
        viewIcon = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        editIcon1 = new javax.swing.JLabel();
        viewIcon1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        editIcon2 = new javax.swing.JLabel();
        viewIcon2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editIcon8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        getContentPane().add(editIcon8, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 350, -1, -1));

        viewIcon8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view.png"))); // NOI18N
        getContentPane().add(viewIcon8, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 350, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 350, -1, -1));

        editIcon7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        getContentPane().add(editIcon7, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 330, -1, -1));

        viewIcon7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view.png"))); // NOI18N
        getContentPane().add(viewIcon7, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 330, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 330, -1, -1));

        editIcon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        getContentPane().add(editIcon6, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 310, -1, -1));

        viewIcon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view.png"))); // NOI18N
        getContentPane().add(viewIcon6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 310, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 310, -1, -1));

        editIcon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        getContentPane().add(editIcon5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 290, -1, -1));

        viewIcon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view.png"))); // NOI18N
        getContentPane().add(viewIcon5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 290, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 290, -1, -1));

        editIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        getContentPane().add(editIcon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 270, -1, -1));

        viewIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view.png"))); // NOI18N
        getContentPane().add(viewIcon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 270, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 270, -1, -1));

        editIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        getContentPane().add(editIcon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 250, -1, -1));

        viewIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view.png"))); // NOI18N
        getContentPane().add(viewIcon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 250, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 250, -1, -1));

        editIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        getContentPane().add(editIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 190, -1, -1));

        viewIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view.png"))); // NOI18N
        getContentPane().add(viewIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 190, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 190, -1, -1));

        editIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        getContentPane().add(editIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 210, -1, -1));

        viewIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view.png"))); // NOI18N
        getContentPane().add(viewIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 210, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 210, -1, -1));

        editIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        getContentPane().add(editIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 230, -1, -1));

        viewIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view.png"))); // NOI18N
        getContentPane().add(viewIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 230, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 230, -1, -1));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setBackground(new java.awt.Color(255, 255, 255));
        jTable2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTable2.setForeground(new java.awt.Color(0, 0, 0));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"05/09/2024", "05/10/2024", "Vaction", "Planned vacation", "Sarah Johnson", ""},
                {"05/09/2024", "05/10/2024", "Sick", "Kidney Operation", "Sarah Johnson", ""},
                {"05/09/2024", "05/10/2024", "Paternal", "Wife Childbirth", "Sarah Johnson", ""},
                {"05/09/2024", "05/10/2024", "Paternal", "Wife Childbirth", "Sarah Johnson", ""},
                {"05/09/2024", "05/10/2024", "Personal", "Therapy", "Sarah Johnson", ""},
                {"05/09/2024", "05/10/2024", "Bereavement", "Grandfather's funeral", "Sarah Johnson", ""},
                {"05/09/2024", "05/10/2024", "Sick", "Covid", "Sarah Johnson", ""},
                {"05/09/2024", "05/10/2024", "Vacation", "Planned Vacation", "Sarah Johnson", ""},
                {"05/09/2024", "05/10/2024", "Sick", "Cold", "Sarah Johnson", ""}
            },
            new String [] {
                "Start Date of Leave", "End Date of Leave", "Leave Type", "Reason for Leave", "Manager", "Actions"
            }
        ));
        jTable2.setToolTipText("");
        jTable2.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 160, 1000, 400));

        jButton1.setBackground(new java.awt.Color(54, 117, 136));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Request Leave");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestLeave(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 90, -1, -1));

        jPanel2.setBackground(new java.awt.Color(54, 117, 136));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Leave Request");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 240, 60));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Logout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3dashboardButton(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 100, -1));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Dashboard");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardButton(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Employee Profile.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void requestLeave(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestLeave
       
        // Treats the RequestLeave Frame as a modal instead of a single page
        new RequestLeave().setVisible(true);
        
    }//GEN-LAST:event_requestLeave

    private void dashboardButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardButton
        
        // Create an instance of the Dashboard frame
        Dashboard dashboard = new Dashboard();
        // Set the visibility of the Dashboard frame to true
        dashboard.setVisible(true);
        // Close the leaveRequest Dashboard frame
        this.dispose(); // Assuming this is the Login frame
        
    }//GEN-LAST:event_dashboardButton

    private void jButton3dashboardButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3dashboardButton
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3dashboardButton

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(leaveRequestDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(leaveRequestDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(leaveRequestDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(leaveRequestDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new leaveRequestDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel editIcon;
    private javax.swing.JLabel editIcon1;
    private javax.swing.JLabel editIcon2;
    private javax.swing.JLabel editIcon3;
    private javax.swing.JLabel editIcon4;
    private javax.swing.JLabel editIcon5;
    private javax.swing.JLabel editIcon6;
    private javax.swing.JLabel editIcon7;
    private javax.swing.JLabel editIcon8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel viewIcon;
    private javax.swing.JLabel viewIcon1;
    private javax.swing.JLabel viewIcon2;
    private javax.swing.JLabel viewIcon3;
    private javax.swing.JLabel viewIcon4;
    private javax.swing.JLabel viewIcon5;
    private javax.swing.JLabel viewIcon6;
    private javax.swing.JLabel viewIcon7;
    private javax.swing.JLabel viewIcon8;
    // End of variables declaration//GEN-END:variables
}
