package Jframes;

import org.jdatepicker.JDatePicker;

public class OvertimeRequest extends javax.swing.JFrame {
    private String userID;

    public OvertimeRequest(String userID) {
        this.userID = userID;
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clockStartTime = new com.raven.swing.TimePicker();
        clockEndTime = new com.raven.swing.TimePicker();
        btnSubmit = new Button.DarkButton();
        btnCancel = new Button.Button();
        btnGoBack = new Button.DarkButton();
        labelOvertimeDate = new javax.swing.JLabel();
        labelRequestOvertime = new javax.swing.JLabel();
        txtOvertimeDate = new com.toedter.calendar.JDateChooser();
        labelStartTime = new javax.swing.JLabel();
        labelEndTime = new javax.swing.JLabel();
        labelTotalHours = new javax.swing.JLabel();
        txtTotalHours = new javax.swing.JFormattedTextField();
        labelReason = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtReason = new javax.swing.JTextArea();
        btnAttachFile = new Button.DarkButton();
        btnDashboard = new Button.Button();
        btnLogout = new Button.Button();
        txtEndTime = new javax.swing.JTextField();
        txtStartTime = new javax.swing.JTextField();
        btnEndTime = new javax.swing.JButton();
        btnStartTime = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        clockStartTime.setForeground(new java.awt.Color(0, 153, 153));
        clockStartTime.setDisplayText(txtStartTime);

        clockEndTime.setForeground(new java.awt.Color(0, 153, 153));
        clockEndTime.setDisplayText(txtEndTime);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1040, 590));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 160, -1));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 160, -1));

        btnGoBack.setText("Go Back");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnGoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 70, -1, -1));

        labelOvertimeDate.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelOvertimeDate.setText("Overtime Date:");
        getContentPane().add(labelOvertimeDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        labelRequestOvertime.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelRequestOvertime.setForeground(new java.awt.Color(255, 255, 255));
        labelRequestOvertime.setText("Request Overtime");
        getContentPane().add(labelRequestOvertime, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 85, -1, -1));
        getContentPane().add(txtOvertimeDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 290, -1));

        labelStartTime.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelStartTime.setText("Start Time: ");
        getContentPane().add(labelStartTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        labelEndTime.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelEndTime.setText("End Time: ");
        getContentPane().add(labelEndTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        labelTotalHours.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelTotalHours.setText("Total Hours:");
        getContentPane().add(labelTotalHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, -1, -1));

        txtTotalHours.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalHoursActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotalHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 120, -1));

        labelReason.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelReason.setText("Reason:");
        getContentPane().add(labelReason, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, -1, -1));

        txtReason.setColumns(20);
        txtReason.setForeground(new java.awt.Color(153, 153, 153));
        txtReason.setRows(5);
        txtReason.setText("Enter a reason for overtime here.");
        jScrollPane2.setViewportView(txtReason);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 310, 140));

        btnAttachFile.setBackground(new java.awt.Color(120, 121, 123));
        btnAttachFile.setForeground(new java.awt.Color(0, 0, 0));
        btnAttachFile.setText("Attach File");
        getContentPane().add(btnAttachFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, -1, -1));

        btnDashboard.setText("Dashboard");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        getContentPane().add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, -1, 30));

        txtEndTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndTimeActionPerformed(evt);
            }
        });
        getContentPane().add(txtEndTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 110, -1));

        txtStartTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStartTimeActionPerformed(evt);
            }
        });
        getContentPane().add(txtStartTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 110, -1));

        btnEndTime.setText("Choose End Time");
        btnEndTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndTimeActionPerformed(evt);
            }
        });
        getContentPane().add(btnEndTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 120, -1));

        btnStartTime.setText("Choose Start Time");
        btnStartTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartTimeActionPerformed(evt);
            }
        });
        getContentPane().add(btnStartTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/For Other Pages.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalHoursActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed

        OvertimeRequestHistory OvertimeRequest = new OvertimeRequestHistory(userID);
        OvertimeRequest.setVisible(true);
        this.dispose(); 
        
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // Create an instance of the Dashboard frame
        HomeDashboard dashboard = new HomeDashboard(userID);
        // Set the visibility of the Dashboard frame to true
        dashboard.setVisible(true);
        // Close the Overtime Request frame
        this.dispose(); // Assuming this is the Login frame
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // Create an instance of LoginNew and display it
        LogInNew loginNew = new LogInNew();
        loginNew.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void txtEndTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndTimeActionPerformed

    private void txtStartTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartTimeActionPerformed

    private void btnStartTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartTimeActionPerformed
        // TODO add your handling code here:
        clockStartTime.showPopup(this, 100, 100);
    }//GEN-LAST:event_btnStartTimeActionPerformed

    private void btnEndTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndTimeActionPerformed
        // TODO add your handling code here:
        clockEndTime.showPopup(this, 100, 100);
    }//GEN-LAST:event_btnEndTimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OvertimeRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OvertimeRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OvertimeRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OvertimeRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private Button.DarkButton btnAttachFile;
    private Button.Button btnCancel;
    private Button.Button btnDashboard;
    private javax.swing.JButton btnEndTime;
    private Button.DarkButton btnGoBack;
    private Button.Button btnLogout;
    private javax.swing.JButton btnStartTime;
    private Button.DarkButton btnSubmit;
    private com.raven.swing.TimePicker clockEndTime;
    private com.raven.swing.TimePicker clockStartTime;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelEndTime;
    private javax.swing.JLabel labelOvertimeDate;
    private javax.swing.JLabel labelReason;
    private javax.swing.JLabel labelRequestOvertime;
    private javax.swing.JLabel labelStartTime;
    private javax.swing.JLabel labelTotalHours;
    private javax.swing.JTextField txtEndTime;
    private com.toedter.calendar.JDateChooser txtOvertimeDate;
    private javax.swing.JTextArea txtReason;
    private javax.swing.JTextField txtStartTime;
    private javax.swing.JFormattedTextField txtTotalHours;
    // End of variables declaration//GEN-END:variables
}
