
package Jframes;

import Classes.db; // Import the db class
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


public class ProfilePage extends javax.swing.JFrame {
    private String userID;
    
    /**
     * Creates new form ProfilePage
     */
    public ProfilePage(String userID) {
        this.userID = userID;
        initComponents();
        fetchData();  // Load profile data based on userID
        
    }
    
    
    
    private void fetchData() {
        try {
            // Get the connection from db class
            Connection conn = db.mycon();

            // Query to get the employeeID based on the userID
            String query = "SELECT employeeID FROM user_accounts WHERE userID = ?";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1, userID);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                String employeeID = rs.getString("employeeID");

                // Now use this employeeID to fetch employee details
                query = "SELECT * FROM employees WHERE employeeID = ?";
                pst = conn.prepareStatement(query);
                pst.setString(1, employeeID);
                rs = pst.executeQuery();

                if (rs.next()) {

                    // Setting the fetched data to labels
                    jEmployeeID.setText(rs.getString("employeeID"));
                    jLastName.setText(rs.getString("lastName"));
                    jFirstName.setText(rs.getString("firstName"));
                    jBirthday.setText(rs.getDate("birthday").toString());
                    jAddress.setText(rs.getString("address"));
                    jPhoneNumber.setText(rs.getString("phoneNumber"));
                    jSssNumber.setText(rs.getString("sssNumber"));
                    jPhilhealthNumber.setText(rs.getString("philhealthNumber"));
                    jTinNumber.setText(rs.getString("tinNumber"));
                    jPagibigNumber.setText(rs.getString("pagibigNumber"));
                    jPosition.setText(rs.getString("position"));
                    jImmediateSupervisor.setText(rs.getString("immediateSupervisor"));
                    jBasicSalary.setText(rs.getBigDecimal("basicSalary").toString());
                    jRiceSubsidy.setText(rs.getBigDecimal("riceSubsidy").toString());
                    jPhoneAllowance.setText(rs.getBigDecimal("phoneAllowance").toString());
                    jClothingAllowance.setText(rs.getBigDecimal("clothingAllowance").toString());
                    jGrossSemiMonthlyRate.setText(rs.getBigDecimal("grossSemiMonthlyRate").toString());
                    jHourlyRate.setText(rs.getBigDecimal("hourlyRate").toString());
                    jStatus.setText(rs.getString("status"));
                } else {
                    System.out.println("No data found for employeeID: " + employeeID);
                }

                // Close the connection
                rs.close();
                pst.close();
                conn.close();
            } else {
                System.out.println("Failed to find employeeID for userID: " + userID);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        employeeProfilePicture = new javax.swing.JLabel();
        dashboardButton = new Button.Button();
        logoutButton = new Button.Button();
        jEmployeeID = new javax.swing.JLabel();
        jPosition = new javax.swing.JLabel();
        jImmediateSupervisor = new javax.swing.JLabel();
        jLastName = new javax.swing.JLabel();
        jFirstName = new javax.swing.JLabel();
        jBirthday = new javax.swing.JLabel();
        jAddress = new javax.swing.JLabel();
        jPhoneNumber = new javax.swing.JLabel();
        jStatus = new javax.swing.JLabel();
        jSssNumber = new javax.swing.JLabel();
        jPagibigNumber = new javax.swing.JLabel();
        jPhilhealthNumber = new javax.swing.JLabel();
        jTinNumber = new javax.swing.JLabel();
        jBasicSalary = new javax.swing.JLabel();
        jRiceSubsidy = new javax.swing.JLabel();
        jPhoneAllowance = new javax.swing.JLabel();
        jClothingAllowance = new javax.swing.JLabel();
        jGrossSemiMonthlyRate = new javax.swing.JLabel();
        jHourlyRate = new javax.swing.JLabel();
        darkButton1 = new Button.DarkButton();
        jPageTitle = new javax.swing.JLabel();
        employeeProfileBackground = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeProfilePicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Persona210x210.png"))); // NOI18N
        getContentPane().add(employeeProfilePicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 210, 210));

        dashboardButton.setText("Dashboard");
        dashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardButtonActionPerformed(evt);
            }
        });
        getContentPane().add(dashboardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, -1, 30));

        jEmployeeID.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jEmployeeID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jEmployeeID.setText("10001");
        getContentPane().add(jEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 230, 30));

        jPosition.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jPosition.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPosition.setText("IT");
        getContentPane().add(jPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 230, 30));

        jImmediateSupervisor.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jImmediateSupervisor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jImmediateSupervisor.setText("Allan Smith");
        getContentPane().add(jImmediateSupervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 230, 30));

        jLastName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLastName.setForeground(new java.awt.Color(54, 117, 136));
        jLastName.setText("Lee");
        getContentPane().add(jLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 167, 120, 30));

        jFirstName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jFirstName.setForeground(new java.awt.Color(54, 117, 136));
        jFirstName.setText("Ging");
        getContentPane().add(jFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 197, 120, 30));

        jBirthday.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBirthday.setForeground(new java.awt.Color(54, 117, 136));
        jBirthday.setText("Jan-01-1990");
        getContentPane().add(jBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 227, 120, 30));

        jAddress.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jAddress.setForeground(new java.awt.Color(54, 117, 136));
        jAddress.setText("123 Luzon, Philippines");
        getContentPane().add(jAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 257, 430, 30));

        jPhoneNumber.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPhoneNumber.setForeground(new java.awt.Color(54, 117, 136));
        jPhoneNumber.setText("09123456789");
        getContentPane().add(jPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 167, -1, 30));

        jStatus.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jStatus.setForeground(new java.awt.Color(54, 117, 136));
        jStatus.setText("Employed");
        getContentPane().add(jStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 200, -1, 30));

        jSssNumber.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jSssNumber.setForeground(new java.awt.Color(54, 117, 136));
        jSssNumber.setText("00-1234567-8");
        getContentPane().add(jSssNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 130, -1));

        jPagibigNumber.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPagibigNumber.setForeground(new java.awt.Color(54, 117, 136));
        jPagibigNumber.setText("987654321000");
        getContentPane().add(jPagibigNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, -1, -1));

        jPhilhealthNumber.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPhilhealthNumber.setForeground(new java.awt.Color(54, 117, 136));
        jPhilhealthNumber.setText("000123456789");
        getContentPane().add(jPhilhealthNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, -1, -1));

        jTinNumber.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTinNumber.setForeground(new java.awt.Color(54, 117, 136));
        jTinNumber.setText("123-456-789-000");
        getContentPane().add(jTinNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, -1, -1));

        jBasicSalary.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBasicSalary.setForeground(new java.awt.Color(54, 117, 136));
        jBasicSalary.setText("50,000.00");
        getContentPane().add(jBasicSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, -1, 20));

        jRiceSubsidy.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jRiceSubsidy.setForeground(new java.awt.Color(54, 117, 136));
        jRiceSubsidy.setText("5,000.00");
        getContentPane().add(jRiceSubsidy, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 350, 70, 20));

        jPhoneAllowance.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPhoneAllowance.setForeground(new java.awt.Color(54, 117, 136));
        jPhoneAllowance.setText("5,000.00");
        getContentPane().add(jPhoneAllowance, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 390, -1, 20));

        jClothingAllowance.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jClothingAllowance.setForeground(new java.awt.Color(54, 117, 136));
        jClothingAllowance.setText("5,000.00");
        getContentPane().add(jClothingAllowance, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 430, 70, 20));

        jGrossSemiMonthlyRate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jGrossSemiMonthlyRate.setForeground(new java.awt.Color(54, 117, 136));
        jGrossSemiMonthlyRate.setText("45,000.00");
        getContentPane().add(jGrossSemiMonthlyRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 470, -1, 20));

        jHourlyRate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jHourlyRate.setForeground(new java.awt.Color(54, 117, 136));
        jHourlyRate.setText("514.00");
        getContentPane().add(jHourlyRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 510, -1, 20));

        darkButton1.setText("Edit");
        getContentPane().add(darkButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 90, 70, -1));

        jPageTitle.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jPageTitle.setForeground(new java.awt.Color(255, 255, 255));
        jPageTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPageTitle.setText("Employee Profile");
        getContentPane().add(jPageTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 78, 290, 50));

        employeeProfileBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Profile Page_Employee.png"))); // NOI18N
        employeeProfileBackground.setText("jLabel3");
        getContentPane().add(employeeProfileBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardButtonActionPerformed
        // Create an instance of the Dashboard frame
        HomeDashboard dashboard = new HomeDashboard(userID);
        // Set the visibility of the Dashboard frame to true
        dashboard.setVisible(true);
        // Close the Profile Page frame
        this.dispose(); // Assuming this is the Login frame
    }//GEN-LAST:event_dashboardButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // Create an instance of LoginNew and display it
        LogInNew loginNew = new LogInNew();
        loginNew.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfilePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Button.DarkButton darkButton1;
    private Button.Button dashboardButton;
    private javax.swing.JLabel employeeProfileBackground;
    private javax.swing.JLabel employeeProfilePicture;
    private javax.swing.JLabel jAddress;
    private javax.swing.JLabel jBasicSalary;
    private javax.swing.JLabel jBirthday;
    private javax.swing.JLabel jClothingAllowance;
    private javax.swing.JLabel jEmployeeID;
    private javax.swing.JLabel jFirstName;
    private javax.swing.JLabel jGrossSemiMonthlyRate;
    private javax.swing.JLabel jHourlyRate;
    private javax.swing.JLabel jImmediateSupervisor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLastName;
    private javax.swing.JLabel jPageTitle;
    private javax.swing.JLabel jPagibigNumber;
    private javax.swing.JLabel jPhilhealthNumber;
    private javax.swing.JLabel jPhoneAllowance;
    private javax.swing.JLabel jPhoneNumber;
    private javax.swing.JLabel jPosition;
    private javax.swing.JLabel jRiceSubsidy;
    private javax.swing.JLabel jSssNumber;
    private javax.swing.JLabel jStatus;
    private javax.swing.JLabel jTinNumber;
    private Button.Button logoutButton;
    // End of variables declaration//GEN-END:variables
}

