
package Jframes;

import java.sql.*;
import javax.swing.JOptionPane;
import Classes.db;



public class UpdateUserAccount extends javax.swing.JFrame {

    private String userID;
    private int employeeID; // declare employeeID as a class-level variable
    private String password;
    private String lastName;
    private String firstName;
    private String position;
    private String userType;
    
    /// Constructor with parameters
    public UpdateUserAccount(String userID, int employeeID, String password, String lastName, String firstName,
                             String position, String userType) {
        initComponents();
        
        // Assign the passed parameters to class-level variables
        this.userID = userID;
        this.employeeID = employeeID;
        this.password = password;
        this.lastName = lastName;
        this.firstName = firstName;
        this.position = position;
        this.userType = userType;

        // Set form fields with passed data
        jUserID.setText(userID);
        jEmployeeID.setText(String.valueOf(employeeID));
        jPassword.setText(password);
        jEmployeeLastName.setText(lastName);
        jEmployeeFirstName.setText(firstName);
        jPosition.setText(position);
        jUserType.setText(userType);
    }

    // Method to clear input fields
    private void clearFields() {
        jUserID.setText("");
        jEmployeeID.setText("");
        jPassword.setText("");
        jEmployeeLastName.setText("");
        jEmployeeFirstName.setText("");
        jPosition.setText("");
        jUserType.setText("");
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEnterDetailsLabel = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jUserID = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jEmployeeID = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jPassword = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jEmployeeLastName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jEmployeeFirstName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPosition = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jUserType = new javax.swing.JTextField();
        button4 = new Button.Button();
        jLabel1 = new javax.swing.JLabel();
        button7 = new Button.Button();
        goBackButton = new Button.DarkButton();
        jUpdateUserAccount = new Button.DarkButton();
        clearButton = new Button.Button();
        backgroundPicture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jEnterDetailsLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jEnterDetailsLabel.setText("Edit User Account Details");
        getContentPane().add(jEnterDetailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel24.setText("User ID:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        jUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserIDActionPerformed(evt);
            }
        });
        getContentPane().add(jUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 150, -1));

        jLabel25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel25.setText("Employee ID:");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        jEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmployeeIDActionPerformed(evt);
            }
        });
        getContentPane().add(jEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 150, -1));

        jLabel23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel23.setText("Password:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));

        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 150, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Last Name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        jEmployeeLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmployeeLastNameActionPerformed(evt);
            }
        });
        getContentPane().add(jEmployeeLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 150, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("First Name:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, -1, -1));

        jEmployeeFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmployeeFirstNameActionPerformed(evt);
            }
        });
        getContentPane().add(jEmployeeFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 150, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Position:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, -1, -1));

        jPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPositionActionPerformed(evt);
            }
        });
        getContentPane().add(jPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 150, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("User Type:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, -1, -1));

        jUserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserTypeActionPerformed(evt);
            }
        });
        getContentPane().add(jUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 150, -1));

        button4.setText("Dashboard");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        getContentPane().add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update a User Account");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 40));

        button7.setText("Logout");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        getContentPane().add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, -1, 30));

        goBackButton.setText("Go Back");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(goBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 70, -1, -1));

        jUpdateUserAccount.setText("Update User Account");
        jUpdateUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateUserAccountActionPerformed(evt);
            }
        });
        getContentPane().add(jUpdateUserAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, -1, -1));

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, 160, -1));

        backgroundPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/For Other Pages.png"))); // NOI18N
        getContentPane().add(backgroundPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        
        AdminHomeDashboard adminDashboard = new AdminHomeDashboard();
        adminDashboard.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_button4ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed

        // Create an instance of LoginNew and display it
        LogInNew loginNew = new LogInNew();
        loginNew.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button7ActionPerformed

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed

        // Redirects to User Accounts Page
        UserAccounts userAccounts = new UserAccounts();
        userAccounts.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_goBackButtonActionPerformed

    private void jUpdateUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateUserAccountActionPerformed
        // Getting the updated data from the form fields
        String userID = jUserID.getText();
        int employeeID = Integer.parseInt(jEmployeeID.getText());
        String password = jPassword.getText();
        String lastName = jEmployeeLastName.getText();
        String firstName = jEmployeeFirstName.getText();
        String position = jPosition.getText();
        String userType = jUserType.getText();

        // SQL Query to update data in MYSQL Database
        String sql = "UPDATE user_accounts SET lastName=?, firstName=?, password=?, position=?, userType=? WHERE userID=? AND employeeID=?";
        
        try (Connection con = db.mycon(); PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, lastName);
            ps.setString(2, firstName);
            ps.setString(3, password);
            ps.setString(4, position);
            ps.setString(5, userType);
            ps.setString(6, userID);
            ps.setInt(7, employeeID);

            ps.executeUpdate();

            // Dialogue Box to inform user that the user account has been updated
            JOptionPane.showMessageDialog(rootPane, "User account details have been updated successfully");
        } catch (SQLException e) {
            e.printStackTrace();
        }

        // Redirects to User Accounts Page
        UserAccounts userAccounts = new UserAccounts();
        userAccounts.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jUpdateUserAccountActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clearFields();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void jUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUserIDActionPerformed

    private void jEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmployeeIDActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jEmployeeLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmployeeLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmployeeLastNameActionPerformed

    private void jEmployeeFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmployeeFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmployeeFirstNameActionPerformed

    private void jPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPositionActionPerformed

    private void jUserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUserTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateUserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateUserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateUserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateUserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundPicture;
    private Button.Button button4;
    private Button.Button button7;
    private Button.Button clearButton;
    private Button.DarkButton goBackButton;
    private javax.swing.JTextField jEmployeeFirstName;
    private javax.swing.JTextField jEmployeeID;
    private javax.swing.JTextField jEmployeeLastName;
    private javax.swing.JLabel jEnterDetailsLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jPassword;
    private javax.swing.JTextField jPosition;
    private Button.DarkButton jUpdateUserAccount;
    private javax.swing.JTextField jUserID;
    private javax.swing.JTextField jUserType;
    // End of variables declaration//GEN-END:variables
}
